global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: 'prometheus'
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
    - auth:3000
    - admin:3000
    - email:3000
    - features:3000
    - search:3000
- job_name: 'Node_Exporter'
  static_configs:
  - targets:
    - node_exporter:9100
- job_name: 'cadvisor'
  static_configs:
  - targets:
    - cadvisor:8080