FROM oven/bun:latest

WORKDIR /app

COPY ./package.json ./package.json
COPY ./bun.lockb ./bun.lockb
COPY ./Webdock-frontend/vite.config.ts ./Webdock-frontend/vite.config.ts

COPY ./Webdock-frontend ./Webdock-frontend

RUN bun install --production

CMD ["bun", "run", "frontend:dev"]

EXPOSE 5173