FROM oven/bun:1.0.18

WORKDIR /app

COPY ./package.json .
COPY ./bun.lockb .
COPY ./prisma ./prisma

RUN bun install --production
RUN bunx prisma generate

COPY ./node_modules/.prisma ./node_modules/.prisma


COPY ./Webdock-auth/src src
COPY ./Webdock-auth/shared shared
COPY ./tsconfig.json .
# COPY public public

ENV NODE_ENV production
CMD ["bun", "src/index.ts"]

EXPOSE 3000