version: 0.0.1

services:
  auth:
    image: franno0/webdock-images:webdock-authv0.0.1
    ports:
      - "3000:3000"
    environment:
      - SECRET=e389bb7b-dc58-4b0b-8f54-dac159d5a609
      - DATABASE_URL=mysql://root:password@DB:3306/features?connect_timeout=600
    links:
      - "DB:DB"
  admin:
    image: franno0/webdock-images:webdock-adminv0.0.1
    ports:
      - "4000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@DB:3306/features?connect_timeout=600
    links:
      - "DB:DB"
  search:
    image: franno0/webdock-images:webdock-searchv0.0.1
    ports:
      - "5000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@DB:3306/features?connect_timeout=600
    links:
      - "DB:DB"
  email:
    image: franno0/webdock-images:webdock-emailv0.0.1
    ports:
      - "6000:3000"
    environment:
      - POSTMARK_TOKEN=c3d41965-18a4-479f-a591-4369b7f5952c
  features:
    image: franno0/webdock-images:webdock-featuresv0.0.1
    ports:
      - "7000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@DB:3306/features?connect_timeout=600
    links:
      - "DB:DB"
  DB:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "features"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db-data:/var/lib/mysql
  prometheus:
    image: prom/prometheus
    user: root
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root
    ports:
      - 9091:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources      
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
volumes:
  db-data:
