version: 0.0.1

services:
  frontend:
    image: franno0/webdock-images:webdock-frontendv1
    ports:
      - "80:5173"
    environment:
      - APIGATEWAY=krakend:8080
  auth:
    image: franno0/webdock-images:webdock-authv0.0.1
    ports:
      - "3000:3000"
    environment:
      - SECRET=e389bb7b-dc58-4b0b-8f54-dac159d5a609
      - DATABASE_URL=mysql://root:password@DB:3306/features?connect_timeout=600
    links:
      - "DB:DB"
  admin:
    image: franno0/webdock-images:webdock-adminv0.0.1
    ports:
      - "4000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@DB:3306/features?connect_timeout=600
    links:
      - "DB:DB"
  search:
    image: franno0/webdock-images:webdock-searchv0.0.1
    ports:
      - "5000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@DB:3306/features?connect_timeout=600
    links:
      - "DB:DB"
  email:
    image: franno0/webdock-images:webdock-emailv0.0.1
    ports:
      - "6000:3000"
    environment:
      - POSTMARK_TOKEN=c3d41965-18a4-479f-a591-4369b7f5952c
      - DATABASE_URL=mysql://root:password@DB:3306/features?connect_timeout=600
  features:
    image: franno0/webdock-images:webdock-featuresv0.0.1
    ports:
      - "7000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@DB:3306/features?connect_timeout=600
    links:
      - "DB:DB"
  sockets:
    image: franno0/webdock-images:webdock-socketsv0.0.1
    ports:
      - "8000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@DB:3306/features?connect_timeout=600
    links:
      - "DB:DB"
  DB:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "features"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
  ###########################################
  #API Gateway #############################
  ##########################################
  krakend:
    image: devopsfaith/krakend
    ports:
      - 8080:8080
    volumes:
      - ./KrakenD/krak.json:/etc/krakend/krakend.json
    restart: unless-stopped
    depends_on:
      - auth
      - admin
      - search
      - email
      - features
      - sockets
