FROM oven/bun:latest

WORKDIR /app

COPY ./package.json .
COPY ./bun.lockb .
COPY ./prisma ./prisma

RUN bun install --production
RUN bunx prisma generate

COPY ./node_modules/.prisma ./node_modules/.prisma

COPY ./Webdock-features/shared shared
COPY ./Webdock-features/src src
COPY ./tsconfig.json .
# COPY public public

ENV NODE_ENV production
CMD ["bun", "src/index.ts"]

EXPOSE 3000